### ISSUE TITLE
Error 111 in urllib/requests causes script to stop

### ISSUE THREAD

**Issue by rmrf-sl4sh** [uosint-project/uosint#6]
When searching for a username, if urllib/requests is refused a connection (in this case, from gitee.com), the script exits. See log portion below:

```
Traceback (most recent call last):
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff7642a9690>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/----/.local/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gitee.com', port=443): Max retries exceeded with url: /------- (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7642a9690>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/----/uosint/uosint.py", line 32, in <module>
    Username_input(usernames=username)
  File "/home/----/uosint/modules/UserName/username.py", line 2910, in Username_input
    GITEE_Request = requests.get(GITEE_URL)
  File "/home/----/.local/lib/python3.10/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/----/.local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/----/.local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/----/.local/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/----/.local/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gitee.com', port=443): Max retries exceeded with url: /------- (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7642a9690>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by uosint-project** [comment]
I'm sorry for showing the error, but I checked the script , it didn't show any error, please tell me the target user name, your OS name, OS version.

Image Url : https://prnt.sc/yvXgfTx4rFfz

**Comment by rmrf-sl4sh** [comment]
> I'm sorry for showing the error, but I checked the script , it didn't show any error, please tell me the target user name, your OS name, OS version.
> 
> Image Url : https://prnt.sc/yvXgfTx4rFfz

I just tried again, using the 'john' username in your example:

```
Traceback (most recent call last):
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f35a4269180>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/----/.local/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/----/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gitee.com', port=443): Max retries exceeded with url: /john (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35a4269180>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/----/uosint/uosint.py", line 32, in <module>
    Username_input(usernames=username)
  File "/home/----/uosint/modules/UserName/username.py", line 2910, in Username_input
    GITEE_Request = requests.get(GITEE_URL)
  File "/home/----/.local/lib/python3.10/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/----/.local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/----/.local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/----/.local/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/----/.local/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gitee.com', port=443): Max retries exceeded with url: /john (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35a4269180>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

OS information:

```
┌──(----㉿kali-2022)-[~/uosint]
└─$ lsb_release -a
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.4
Codename:       kali-rolling
```

**Comment by uosint-project** [comment]
> > I'm sorry for showing the error, but I checked the script , it didn't show any error, please tell me the target user name, your OS name, OS version.
> > Image Url : https://prnt.sc/yvXgfTx4rFfz
> 
> I just tried again, using the 'john' username in your example:
> 
> ```
> Traceback (most recent call last):
>   File "/home/----/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/home/----/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
>     raise err
>   File "/home/----/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
>     httplib_response = self._make_request(
>   File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
>     self._validate_conn(conn)
>   File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
>     conn.connect()
>   File "/home/----/.local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
>     self.sock = conn = self._new_conn()
>   File "/home/----/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f35a4269180>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/----/.local/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/home/----/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
>     retries = retries.increment(
>   File "/home/----/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gitee.com', port=443): Max retries exceeded with url: /john (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35a4269180>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/----/uosint/uosint.py", line 32, in <module>
>     Username_input(usernames=username)
>   File "/home/----/uosint/modules/UserName/username.py", line 2910, in Username_input
>     GITEE_Request = requests.get(GITEE_URL)
>   File "/home/----/.local/lib/python3.10/site-packages/requests/api.py", line 76, in get
>     return request('get', url, params=params, **kwargs)
>   File "/home/----/.local/lib/python3.10/site-packages/requests/api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/home/----/.local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/----/.local/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/----/.local/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gitee.com', port=443): Max retries exceeded with url: /john (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35a4269180>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ```
> 
> OS information:
> 
> ```
> ┌──(----㉿kali-2022)-[~/uosint]
> └─$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Kali
> Description:    Kali GNU/Linux Rolling
> Release:        2022.4
> Codename:       kali-rolling
> ```




This is a traceback of an error that occurred in a Python script. The error message suggests that there was an issue with the script trying to establish a new connection when making a GET request to the URL 'gitee.com' using the requests library. Specifically, it is raising a "ConnectionRefusedError: [Errno 111] Connection refused" error, which can happen when the server or network is down, or the script is trying to connect to an incorrect address.
It looks like the code is trying to access a user profile on gitee.com and the error is occurring on line 2910 of the file '/home/----/uosint/modules/UserName/username.py' where the script is trying to make a GET request to the GITEE_URL.
It might be possible that the website is down or there might be an issue with the internet connection.

You can check for the website status and also check your internet connection to troubleshoot the error.


I got 2 solutions here is :

Solution No 1 :-

1.  Check All Module Install like requirements.txt and urllib
2.  Use VPN when you run this tool

Solution No 2 :-

1.  Remove 2906 to 2942 Line 
2. PATH is "uosint/modules/UserName/username.py" save and run
